"""Plain-language layer for ClimAID v2 reports.

The technical C-DSI v2 interpretation is precise but written for modellers
(WIS, quantiles, hindcasts, coverage). This module turns the same numbers into
short, everyday sentences for health officers, planners and the public. Like
C-DSI it is fully deterministic: every sentence comes from fixed rules applied
to the run's own numbers; nothing is generated by an LLM.

Conventions used in all plain text
----------------------------------
- "Likely range" = the 80% interval: in 8 out of 10 cases the real number
  should fall inside it.
- "Typical year" = the average for the same calendar month over the last (up
  to) five years before the forecast start, leaving out replaced months.
- Numbers are rounded to whole cases; percentages to whole numbers.
"""
from __future__ import annotations

import html
import numpy as np
import pandas as pd

GLOSSARY_FORECAST = [
    ("Forecast", "Our best estimate of how many cases there will be, made using only information available before the forecast start."),
    ("Likely range", "The range the real number should fall inside 8 times out of 10. Wider ranges mean more uncertainty."),
    ("Typical year", "The average number of cases in the same month over the last five years."),
    ("Model", "A set of calculations that learns from past cases and weather to estimate future cases. Several are compared and the one that did best in past tests is shown."),
    ("Past tests", "We pretended to be at earlier dates, made forecasts, and checked them against what really happened."),
    ("Ensemble", "A combination of all the models, taking their middle value."),
]
GLOSSARY_SCENARIO = [
    ("Emissions pathway", "A possible future for how much greenhouse gas the world emits. Scientists use standard pathways (SSPs) so studies can be compared."),
    ("Climate model", "A computer simulation of the world's climate. Different ones give somewhat different futures, so we use several."),
    ("Baseline", "The average number of cases per year in the historical period we compare against."),
    ("Likely range", "The range the result should fall inside 8 times out of 10, given climate-model and statistical uncertainty."),
    ("Projection", "A 'what if' estimate: what could happen if the climate changes in a given way and everything else stays the same. It is not a prediction of the actual future."),
]
SSP_PLAIN = {
    "ssp119": "Very low emissions (rapid climate action)",
    "ssp126": "Low emissions (strong climate action)",
    "ssp245": "Middle-of-the-road emissions",
    "ssp370": "High emissions",
    "ssp460": "Medium-high emissions",
    "ssp585": "Very high emissions (fossil-fuel intensive)",
}
MODEL_PLAIN = {
    "ensemble": "combined forecast (all methods together)", "seasonal_naive": "“same as recent years” method",
    "renewal": "transmission model", "poisson": "Poisson regression", "random_forest": "random forest",
    "extra_trees": "extra trees", "gradient_boosting": "gradient boosting", "xgboost": "XGBoost",
    "lightgbm": "LightGBM", "catboost": "CatBoost", "mlp": "neural network", "linear": "linear regression",
    "ridge": "ridge regression", "lasso": "lasso regression", "elasticnet": "elastic-net regression",
    "tweedie": "Tweedie regression", "spline_poisson": "smooth-curve Poisson model", "bayesian_ridge": "Bayesian ridge regression",
    "huber": "spike-resistant (Huber) regression", "hist_gradient_boosting": "fast gradient boosting",
    "svr": "support vector regression", "knn": "nearest-neighbour method", "v1_stack": "ClimAID v1 stacked model",
    "sarimax": "SARIMAX time-series model",
}
RATING_STYLE = {"Good": "good", "Moderate": "moderate", "Low": "low", "Not tested": "unknown"}


def _n(x):
    """Whole number with thousands separators."""
    try:
        return f"{int(round(float(x))):,}"
    except Exception:
        return "—"


def _month(t):
    return pd.Timestamp(t).strftime("%B %Y")


def _glossary(items):
    return "<dl class='glossary'>" + "".join(
        f"<dt>{html.escape(k)}</dt><dd>{html.escape(v)}</dd>" for k, v in items) + "</dl>"


def _rating_badge(rating):
    return f"<span class='rating {RATING_STYLE.get(rating, 'unknown')}'>{html.escape(rating)}</span>"


# ---------------------------------------------------------------------------
# forecast report
# ---------------------------------------------------------------------------
def select_primary_model(forecasts, metrics, hindcast_metrics):
    """Same rule as C-DSI v2: best mean hindcast WIS, else best held-out WIS,
    else the ensemble, else the first model. Returns (name, source)."""
    from climaid.reporting_v2 import _rank_models_by_wis
    for table, source in ((hindcast_metrics, "past tests"), (metrics, "the months already observed")):
        ranked = [(m, w) for m, w in _rank_models_by_wis(table) if m in forecasts]
        if ranked:
            return ranked[0][0], source
    if "ensemble" in forecasts:
        return "ensemble", None
    return next(iter(forecasts)), None


def _typical_by_month(history, exclude_times=(), years=5):
    if history is None or len(history) == 0:
        return None
    h = history.copy()
    h["time"] = pd.to_datetime(h["time"])
    col = "cases" if "cases" in h.columns else [c for c in h.columns if c != "time"][0]
    if len(exclude_times):
        h = h[~h["time"].isin(pd.to_datetime(list(exclude_times)))]
    last = h["time"].dt.year.max()
    h = h[h["time"].dt.year > last - years]
    return h.groupby(h["time"].dt.month)[col].mean()


def _metric(table, model, col):
    if table is None or table.empty or "model" not in table.columns or col not in table.columns:
        return None
    v = pd.to_numeric(table.loc[table["model"] == model, col], errors="coerce").dropna()
    return float(v.mean()) if len(v) else None


def forecast_trust(forecasts, primary, metrics, hindcast_metrics, horizon):
    """Deterministic Good / Moderate / Low rating with plain reasons.

    One point each for: (1) the likely range contained the real value about as
    often as it should (65-95% of months for an 80% range); (2) the chosen
    method beat the simple "same as last year" method in past tests; (3) the
    methods broadly agree; (4) the forecast is at most 12 months ahead.
    4 = Good, 2-3 = Moderate, 0-1 = Low. "Not tested" if no checks exist.
    """
    reasons, points, tested = [], 0, False
    cov = _metric(metrics, primary, "coverage_80")
    cov_src = "the months we could already check"
    if cov is None:
        cov = _metric(hindcast_metrics, primary, "coverage_80"); cov_src = "past tests"
    if cov is not None:
        tested = True
        hit = f"{cov * 10:.0f} out of 10"
        if 0.65 <= cov <= 0.95:
            points += 1
            reasons.append(f"In {cov_src}, the real number fell inside the likely range {hit} times, which is about right.")
        elif cov < 0.65:
            reasons.append(f"In {cov_src}, the real number fell inside the likely range only {hit} times (it should be about 8), so real numbers may fall outside it more often than shown.")
        else:
            points += 0.5
            reasons.append(f"In {cov_src}, the real number fell inside the likely range {hit} times, so the range may be wider than it needs to be.")
    w_p = _metric(hindcast_metrics, primary, "WIS") or _metric(metrics, primary, "WIS")
    w_s = _metric(hindcast_metrics, "seasonal_naive", "WIS") or _metric(metrics, "seasonal_naive", "WIS")
    if primary == "seasonal_naive" and w_p is not None:
        tested = True
        reasons.append("The simplest method (assume this year will look like recent years) did best in past tests, so the more complex climate models are not adding much here.")
    elif w_p is not None and w_s is not None:
        tested = True
        if w_p < w_s:
            points += 1
            reasons.append(f"The {MODEL_PLAIN.get(primary, primary)} was about {100 * (1 - w_p / w_s):.0f}% more accurate in past tests than simply assuming this year will look like recent years.")
        else:
            reasons.append(f"The {MODEL_PLAIN.get(primary, primary)} was not more accurate in past tests than simply assuming this year will look like recent years.")
    tot = {k: float(v["q500"].sum()) for k, v in forecasts.items() if k != "ensemble" and "q500" in v}
    if len(tot) >= 2:
        lo, hi = min(tot.values()), max(tot.values())
        if hi <= 2 * max(lo, 1):
            points += 1
            reasons.append("The different methods broadly agree.")
        else:
            reasons.append(f"The different methods disagree a lot: their totals range from about {_n(lo)} to {_n(hi)} cases.")
    else:
        points += 1
    if horizon <= 12:
        points += 1
    else:
        reasons.append(f"The forecast runs {horizon} months ahead; beyond about a year it mostly reflects the usual seasonal pattern and is much less certain.")
    if not tested:
        return "Not tested", ["There was no past data to test these methods against, so we cannot say how reliable they are."]
    rating = "Good" if points >= 4 else ("Moderate" if points >= 2 else "Low")
    return rating, reasons


def plain_forecast_html(*, forecasts, metrics, hindcast_metrics, metadata, disease_name, district,
                        history=None, observed=None, exclude_times=()):
    """Return (summary_html, month_table_html, trust_html, notes_html, glossary_html, primary)."""
    primary, source = select_primary_model(forecasts, metrics, hindcast_metrics)
    f = forecasts[primary].copy(); f["time"] = pd.to_datetime(f["time"])
    typical = _typical_by_month(history, exclude_times)
    obs = None
    if observed is not None and len(observed):
        o = observed.copy(); o["time"] = pd.to_datetime(o["time"])
        col = "cases" if "cases" in o.columns else [c for c in o.columns if c != "time"][0]
        obs = o.set_index("time")[col]
    horizon = len(f)
    lo_c, hi_c = ("q100", "q900") if {"q100", "q900"} <= set(f.columns) else ("q025", "q975")

    # --- month-by-month table
    rows, flags = [], []
    for _, r in f.iterrows():
        exp, lo, hi = r["q500"], r[lo_c], r[hi_c]
        cells = [_month(r["time"]), _n(exp), f"{_n(lo)} to {_n(hi)}"]
        if typical is not None:
            t = typical.get(r["time"].month, np.nan)
            if np.isfinite(t):
                if exp > 1.25 * t and exp - t >= 2:
                    lab, cls = "Higher than usual", "up"
                elif exp < 0.8 * t and t - exp >= 2:
                    lab, cls = "Lower than usual", "down"
                else:
                    lab, cls = "About usual", "same"
                flags.append(cls)
                cells.append(f"<span class='cmp {cls}'>{lab}</span> <span class='muted'>(usually {_n(t)})</span>")
            else:
                cells.append("—")
        if obs is not None:
            y = obs.get(r["time"], np.nan)
            if np.isfinite(y):
                inside = lo <= y <= hi
                cells.append(f"{_n(y)} {'<span class=ok>✓ inside range</span>' if inside else '<span class=miss>✗ outside range</span>'}")
            else:
                cells.append("<span class='muted'>not yet known</span>")
        rows.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
    head = ["Month", "Expected cases", "Likely range<br><span class='muted'>(8 in 10 chance)</span>"]
    if typical is not None:
        head.append("Compared with a typical year")
    if obs is not None:
        head.append("What actually happened")
    table = ("<table class='plain'><thead><tr>" + "".join(f"<th>{h}</th>" for h in head) +
             "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>")

    # --- short version
    total = f["q500"].sum()
    pk = f.loc[f["q500"].idxmax()]
    first, last = _month(f["time"].min()), _month(f["time"].max())
    bullets = [f"From <strong>{first}</strong> to <strong>{last}</strong>, we expect about "
               f"<strong>{_n(total)} {html.escape(disease_name)} cases</strong> in {html.escape(_district_name(district))} in total."]
    pk_text = f"The busiest month is likely to be <strong>{pd.Timestamp(pk['time']).strftime('%B')}</strong>, with around {_n(pk['q500'])} cases"
    pk_text += f" (likely between {_n(pk[lo_c])} and {_n(pk[hi_c])})."
    bullets.append(pk_text)
    if typical is not None:
        t_tot = sum(typical.get(m, np.nan) for m in f["time"].dt.month)
        if np.isfinite(t_tot) and t_tot > 0:
            ch = total / t_tot - 1
            word = ("higher than" if ch > 0.15 else "lower than" if ch < -0.15 else "similar to")
            pct = f" (about {abs(ch) * 100:.0f}% {'more' if ch > 0 else 'fewer'})" if word != "similar to" else ""
            bullets.append(f"Overall, this is <strong>{word}</strong> a typical year{pct}.")
            names = [pd.Timestamp(t).strftime("%B") for t in f["time"]]
            ups = [n for n, c in zip(names, flags) if c == "up"]
            downs = [n for n, c in zip(names, flags) if c == "down"]
            parts = []
            if ups:
                parts.append(f"higher than usual in <strong>{_list(ups)}</strong>")
            if downs:
                parts.append(f"lower than usual in <strong>{_list(downs)}</strong>")
            if parts:
                bullets.append(("But cases are expected to be " if word == "similar to" else "Cases are expected to be ")
                               + " and ".join(parts) + ".")
    rating, reasons = forecast_trust(forecasts, primary, metrics, hindcast_metrics, horizon)
    bullets.append(f"How much to trust this: {_rating_badge(rating)} — see “How much can you trust this?” below.")
    if obs is not None:
        known = [(r[lo_c] <= obs.get(r["time"], np.nan) <= r[hi_c]) for _, r in f.iterrows() if np.isfinite(obs.get(r["time"], np.nan))]
        if known:
            bullets.append(f"We can already check {len(known)} of these months: the real number was inside the likely range in "
                           f"<strong>{sum(known)}</strong> of them.")
    summary = "<ul class='summary'>" + "".join(f"<li>{b}</li>" for b in bullets) + "</ul>"
    why = {"past tests": "because it did best in past tests", "the months already observed":
           "because it did best on the months already observed"}.get(source, "")
    table = (f"<p class='muted'>Figures come from the {html.escape(MODEL_PLAIN.get(primary, primary))} {why}. "
             "Red and green labels compare each month with the same month in a typical year.</p>") + table

    trust = (f"<p class='rating-line'>{_rating_badge(rating)}</p><ul>" +
             "".join(f"<li>{html.escape(x)}</li>" for x in reasons) + "</ul>" +
             "<p class='muted'>How the rating is worked out: one point each for (1) the likely range containing the real "
             "number about as often as it should, (2) beating the simple “same as recent years” method, (3) the methods "
             "agreeing, and (4) looking no more than 12 months ahead. 4 points = Good, 2–3 = Moderate, 0–1 = Low.</p>")

    notes = []
    ex = metadata.get("excluded_period") or ("2020" if metadata.get("drop_2020") else None)
    if ex and metadata.get("excluded_months", 1):
        when = f"in {ex}" if ex.isdigit() else f"from {ex}"
        notes.append(f"Case counts {when} were treated as unreliable (COVID-19 disrupted testing and reporting), "
                     "so they were replaced with typical values when training the models.")
    src = str(metadata.get("forecast_climate_source") or "")
    if "observed" in src:
        notes.append("This forecast used the weather that was actually recorded for these months. A real forecast made in advance would have to rely on predicted weather and would be less certain.")
    elif "projection" in src.lower():
        notes.append("This forecast used climate-model projections for the weather in these months, not observed weather.")
    if not metadata.get("population_available"):
        notes.append("The number of people at risk was not supplied, so the forecast cannot account for immunity building up during a large outbreak.")
    if any("stability cap" in str(w) for w in metadata.get("warnings", [])):
        notes.append("One of the methods (the transmission model) predicted runaway growth and had to be limited; its results are less reliable.")
    if metadata.get("interval_calibration"):
        notes.append("The likely ranges were widened (or narrowed) based on how accurate the methods were in past tests, so they reflect real-world accuracy rather than the models' own confidence.")
    notes.append("The forecast assumes testing, reporting and control efforts stay as they were. Changes in any of these will change the real numbers.")
    notes_html = "<ul>" + "".join(f"<li>{html.escape(n)}</li>" for n in notes) + "</ul>"

    return summary, table, trust, notes_html, _glossary(GLOSSARY_FORECAST), primary, (f, lo_c, hi_c, typical, obs)


def _list(items):
    items = list(items)
    return items[0] if len(items) == 1 else ", ".join(items[:-1]) + " and " + items[-1]


def _district_name(d):
    parts = str(d).split("_")
    return parts[1].replace("-", " ").title() if len(parts) >= 3 else str(d).replace("_", " ")


def plain_forecast_chart(f, lo_c, hi_c, typical, obs, disease_name):
    import plotly.graph_objects as go
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=f["time"], y=f[hi_c], mode="lines", line=dict(width=0), showlegend=False, hoverinfo="skip"))
    fig.add_trace(go.Scatter(x=f["time"], y=f[lo_c], mode="lines", fill="tonexty", line=dict(width=0),
                             fillcolor="rgba(37,99,235,0.18)", name="Likely range (8 in 10 chance)", hoverinfo="skip"))
    fig.add_trace(go.Scatter(x=f["time"], y=f["q500"], mode="lines", line=dict(color="#1d4ed8", width=3), name="Expected cases",
                             hovertemplate="%{x|%B %Y}: about %{y:.0f} cases<extra></extra>"))
    if typical is not None:
        fig.add_trace(go.Scatter(x=f["time"], y=[typical.get(t.month, np.nan) for t in f["time"]],
                                 mode="lines", line=dict(color="#6b7280", dash="dash", width=2), name="Typical year",
                                 hovertemplate="%{x|%B}: usually %{y:.0f} cases<extra></extra>"))
    if obs is not None:
        o = obs[obs.index.isin(f["time"])]
        if len(o):
            fig.add_trace(go.Scatter(x=o.index, y=o.values, mode="markers", marker=dict(color="#111827", size=9),
                                     name="What actually happened", hovertemplate="%{x|%B %Y}: %{y:.0f} cases<extra></extra>"))
    fig.update_layout(template="plotly_white", height=420, margin=dict(l=40, r=20, t=30, b=40),
                      yaxis_title=f"{disease_name} cases per month", legend=dict(orientation="h", y=-0.18),
                      font=dict(size=14))
    return fig.to_html(full_html=False, include_plotlyjs=True, config={"displayModeBar": False})


# ---------------------------------------------------------------------------
# scenario report
# ---------------------------------------------------------------------------
def scenario_trust(outlook, sensitivity=None, backtest=None):
    """Good / Moderate / Low confidence in the scenario projections, with reasons.

    One point each for: (1) the backtest on held-out years was not worse than
    repeating the historical average; (2) the climate models agree on the
    direction of change (>= 80% of outcomes the same way in the last decade);
    (3) results are not highly sensitive to how climate effects are learned
    (<= 10 percentage points); (4) the data could pin down which climate factors
    matter (at most 2 near-equally-good explanations). 4 = Good, 2-3 = Moderate,
    0-1 = Low.
    """
    reasons, points = [], 0
    dec, meta = outlook.decades, outlook.metadata
    if backtest and backtest.get("summary") and "median_abs_pct_error" in backtest["summary"]:
        sm = backtest["summary"]
        e, e0 = sm["median_abs_pct_error"], sm["median_abs_pct_error_training_mean"]
        if e <= 1.2 * e0:
            points += 1
            reasons.append(f"When we tested the method on {sm['n_years']} past years it had not seen, it was about as accurate as "
                           f"or better than simply using the historical average (typical error {e:.0%}).")
        else:
            reasons.append(f"When tested on {sm['n_years']} past years it had not seen, it was less accurate than simply using the historical average.")
    else:
        reasons.append("The method could not be tested on past years.")
    if not dec.empty:
        last = sorted(dec["decade"].unique())[-1]
        shares = dec[dec.decade == last]["share_gcm_samples_increase"]
        agree = shares.map(lambda x: max(x, 1 - x)).min()
        if agree >= 0.8:
            points += 1
            reasons.append("The climate models mostly agree on whether cases go up or down.")
        else:
            reasons.append("The climate models do not agree on whether cases will go up or down.")
    if sensitivity is not None and not dec.empty and not sensitivity.decades.empty:
        last = sorted(dec["decade"].unique())[-1]
        a = dec[dec.decade == last].set_index("ssp").change_vs_baseline_median
        b = sensitivity.decades[sensitivity.decades.decade == last].set_index("ssp").change_vs_baseline_median
        gap = (a - b).abs().max()
        if np.isfinite(gap) and gap <= 0.10:
            points += 1
            reasons.append("The results hold up when we change how the effect of climate is estimated.")
        else:
            reasons.append(f"The results change noticeably (by up to {gap * 100:.0f} percentage points) depending on how the effect of climate is estimated.")
    n_struct = len(meta.get("lag_structures") or [])
    if n_struct <= 2:
        points += 1
    else:
        reasons.append(f"The past data fit {n_struct} different explanations about equally well (for example, whether heat or rain matters more). "
                       "They predict different amounts of change, so the likely range is wide.")
    rating = "Good" if points >= 4 else ("Moderate" if points >= 2 else "Low")
    return rating, reasons


def plain_scenario_html(outlook, *, disease_name, district, sensitivity=None, backtest=None):
    dec, base, meta = outlook.decades, outlook.baseline, outlook.metadata
    place = html.escape(_district_name(district)); dis = html.escape(disease_name)
    bullets = []
    if not dec.empty:
        decades = sorted(dec["decade"].unique())
        last = decades[-1]
        for s in meta["ssps"]:
            r = dec[(dec.ssp == s) & (dec.decade == last)]
            if r.empty:
                continue
            r = r.iloc[0]
            ch, lo, hi = r.change_vs_baseline_median, r.change_p10, r.change_p90
            more = r.annual_median - base["model_annual_mean"]
            dirw = "more" if ch >= 0 else "fewer"
            bullets.append(
                f"<strong>{html.escape(SSP_PLAIN.get(s, s.upper()))}:</strong> by the <strong>{last}</strong>, about "
                f"<strong>{_n(r.annual_median)} cases a year</strong> — roughly {abs(ch) * 100:.0f}% {dirw} than in "
                f"{base['years']} ({_n(abs(more))} {dirw} cases a year). "
                f"Likely range: {_range_words(lo, hi)}.")
        if len(meta["ssps"]) > 1:
            bullets.append(_pathway_comparison(dec, decades))
    rating, reasons = scenario_trust(outlook, sensitivity, backtest)
    bullets.append(f"Confidence in these projections: {_rating_badge(rating)} — see below.")
    summary = (f"<p class='lede'>What could happen to {dis} in {place} as the climate changes, if everything else "
               f"(population, mosquito control, testing) stayed the same as in {base['years']}.</p>"
               "<ul class='summary'>" + "".join(f"<li>{b}</li>" for b in bullets) + "</ul>")
    trust = (f"<p class='rating-line'>{_rating_badge(rating)}</p><ul>" +
             "".join(f"<li>{html.escape(x)}</li>" for x in reasons) + "</ul>" +
             "<p class='muted'>How the rating is worked out: one point each for (1) doing at least as well as the historical "
             "average on past years it had not seen, (2) the climate models agreeing on the direction of change, (3) results "
             "holding up under a different way of estimating climate effects, and (4) the data pointing to a clear "
             "explanation. 4 points = Good, 2–3 = Moderate, 0–1 = Low.</p>")
    not_incl = ["Changes in population. " + ("A separate table in the technical details shows results with projected population." if getattr(outlook, "decades_with_population", None) is not None else "More people usually means more cases."),
                "Changes in mosquito control, housing, water storage, testing or reporting.",
                "New virus strains or changes in immunity.",
                "Extreme events such as floods, which can cause outbreaks the monthly averages do not capture."]
    notes = "<ul>" + "".join(f"<li>{html.escape(x)}</li>" for x in not_incl) + "</ul>"
    return summary, trust, notes, _glossary(GLOSSARY_SCENARIO)


def _pathway_comparison(dec, decades):
    """Compare emissions pathways from the numbers, never by assumption."""
    first, last = decades[0], decades[-1]
    # use the same rounded percentages the reader sees, so the stated gap matches
    g = lambda d: (dec[dec.decade == d].change_vs_baseline_median * 100).round()
    gap0, gap1 = float(g(first).max() - g(first).min()) / 100, float(g(last).max() - g(last).min()) / 100
    rows = dec[dec.decade == last]
    overlap = rows.change_p10.max() <= rows.change_p90.min()
    if gap1 >= 0.05 and gap1 - gap0 >= 0.05:
        txt = (f"The gap between the pathways grows over time: about {gap0 * 100:.0f} percentage points in the {first}, "
               f"about {gap1 * 100:.0f} by the {last}. What the world does about emissions matters more further ahead.")
        if overlap:
            txt += " Their likely ranges overlap, so the difference is not certain."
    else:
        txt = (f"The pathways give similar results (within about {gap1 * 100:.0f} percentage points by the {last}), "
               f"so up to then the choice of pathway makes less difference than the other uncertainties.")
    return txt


def _range_words(lo, hi):
    def w(x):
        return f"{abs(x) * 100:.0f}% {'more' if x >= 0 else 'fewer'}"
    if lo >= 0 or hi <= 0:
        return f"from {w(lo)} to {w(hi)}"
    return f"from {w(lo)} to {w(hi)} — so a decrease cannot be ruled out"


def partner_logo_html():
    """NDMC logo on a white badge for the dark report header (embedded, so reports stay self-contained)."""
    import base64
    from pathlib import Path
    path = Path(__file__).parent / "assets" / "ndmc_logo.png"
    if not path.exists():
        return ""
    b64 = base64.b64encode(path.read_bytes()).decode()
    return ("<div class='partner-badge'><img src='data:image/png;base64," + b64 +
            "' alt='National Disease Modelling Consortium (NDMC)'></div>")


PLAIN_CSS = """
header{display:flex;justify-content:space-between;align-items:center;gap:20px}
.partner-badge{background:#fff;border-radius:12px;padding:8px 12px;flex-shrink:0}
.partner-badge img{height:48px;display:block}
@media(max-width:700px){header{flex-direction:column;align-items:flex-start}.partner-badge img{height:36px}}
.plain-intro{font-size:17px;line-height:1.6}
.summary{font-size:17px;line-height:1.65;padding-left:22px}.summary li{margin:10px 0}
.lede{font-size:17px;color:#374151;margin-top:0}
table.plain{width:100%;border-collapse:collapse;font-size:15px}
table.plain th{background:#f3f4f6;text-align:left;padding:10px;font-weight:600}
table.plain td{padding:10px;border-bottom:1px solid #eceff3;text-align:left}
.cmp{font-weight:600;border-radius:99px;padding:2px 10px;font-size:13px;white-space:nowrap}
.cmp.up{background:#fee2e2;color:#991b1b}.cmp.down{background:#dcfce7;color:#166534}.cmp.same{background:#f3f4f6;color:#374151}
.ok{color:#166534;font-weight:600}.miss{color:#991b1b;font-weight:600}
.rating{display:inline-block;border-radius:99px;padding:3px 12px;font-weight:700;font-size:14px}
.rating.good{background:#dcfce7;color:#166534}.rating.moderate{background:#fef3c7;color:#92400e}
.rating.low{background:#fee2e2;color:#991b1b}.rating.unknown{background:#e5e7eb;color:#374151}
.rating-line{font-size:18px;margin:4px 0 8px}
dl.glossary{display:grid;grid-template-columns:max-content 1fr;gap:8px 18px;font-size:15px;margin:0}
dl.glossary dt{font-weight:600}dl.glossary dd{margin:0;color:#374151}
details.tech{background:#fff;border:1px solid #e6e8eb;border-radius:16px;padding:6px 20px;margin-bottom:18px}
details.tech>summary{cursor:pointer;font-weight:700;font-size:17px;padding:12px 0}
details.tech[open]>summary{margin-bottom:10px}
@media(max-width:600px){dl.glossary{grid-template-columns:1fr}table.plain{font-size:13px}}
"""

RESIZE_JS = ("<script>document.querySelectorAll('details.tech').forEach(d=>d.addEventListener('toggle',()=>"
             "window.dispatchEvent(new Event('resize'))));</script>")
